# Generated by Django 5.0 on 2023-12-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='content/image')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(upload_to='team/profile')),
                ('post', models.CharField(max_length=20)),
                ('facebook_link', models.URLField(blank=True, default=True)),
                ('linkedin_link', models.URLField(blank=True, default=True)),
                ('instagram_link', models.URLField(blank=True, default=True)),
            ],
        ),
    ]
