# Generated by Django 5.0 on 2023-12-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='blog')),
                ('description', models.TextField()),
                ('post_link', models.URLField(blank=True)),
            ],
        ),
    ]
